//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordsCounter.Resources.Partials {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SummaryInformation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SummaryInformation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordsCounter.Resources.Partials.SummaryInformation", typeof(SummaryInformation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlphaCharacters.
        /// </summary>
        public static string AlphaCharacters {
            get {
                return ResourceManager.GetString("AlphaCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlphanumericCharacters.
        /// </summary>
        public static string AlphanumericCharacters {
            get {
                return ResourceManager.GetString("AlphanumericCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters.
        /// </summary>
        public static string Characters {
            get {
                return ResourceManager.GetString("Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CharactersWithoutSpace.
        /// </summary>
        public static string CharactersWithoutSpace {
            get {
                return ResourceManager.GetString("CharactersWithoutSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LongWords.
        /// </summary>
        public static string LongWords {
            get {
                return ResourceManager.GetString("LongWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumericCharacters.
        /// </summary>
        public static string NumericCharacters {
            get {
                return ResourceManager.GetString("NumericCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragraphs.
        /// </summary>
        public static string Paragraphs {
            get {
                return ResourceManager.GetString("Paragraphs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentences.
        /// </summary>
        public static string Sentences {
            get {
                return ResourceManager.GetString("Sentences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShortWords.
        /// </summary>
        public static string ShortWords {
            get {
                return ResourceManager.GetString("ShortWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UniqueWords.
        /// </summary>
        public static string UniqueWords {
            get {
                return ResourceManager.GetString("UniqueWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Words.
        /// </summary>
        public static string Words {
            get {
                return ResourceManager.GetString("Words", resourceCulture);
            }
        }
    }
}
